name: Unit tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
        python -m adeft.download
    - name: Tests
      run: |
        export NOSE_IGNORE_FILES="generate_terms.py";
        nosetests gilda/tests -v --with-coverage --cover-inclusive --cover-package=gilda
